import WebSocket from 'ws';
import { chunkBuffer, mulawToPcm16, pcm16ToMulaw, resamplePcm16 } from './audio.js';
export class GeminiLivePhoneBridge{
  private socket?:WebSocket;private ready=false;private queue:string[]=[];private closed=false;
  constructor(private instruction:string,private streamSid:string,private sendTwilio:(message:object)=>void){}
  connect(){const key=process.env.GEMINI_API_KEY;if(!key)return false;this.socket=new WebSocket(`wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContent?key=${encodeURIComponent(key)}`,{maxPayload:2*1024*1024,perMessageDeflate:false});this.socket.on('open',()=>this.socket?.send(JSON.stringify({setup:{model:`models/${process.env.GEMINI_LIVE_MODEL??'gemini-3.8-live'}`,responseModalities:['AUDIO'],systemInstruction:{parts:[{text:this.instruction}]},generationConfig:{speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:process.env.GEMINI_VOICE??'Kore'}}}}}})));this.socket.on('message',data=>this.receive(data.toString()));this.socket.on('close',()=>this.ready=false);this.socket.on('error',()=>this.ready=false);return true}
  sendMulaw(base64:string){if(this.closed)return;const pcm16=resamplePcm16(mulawToPcm16(Buffer.from(base64,'base64')),8000,16000);const message=JSON.stringify({realtimeInput:{audio:{data:pcm16.toString('base64'),mimeType:'audio/pcm;rate=16000'}}});if(this.ready&&this.socket?.readyState===WebSocket.OPEN)this.socket.send(message);else if(this.queue.length<100)this.queue.push(message)}
  private receive(raw:string){const event=JSON.parse(raw);if(event.setupComplete){this.ready=true;for(const message of this.queue)this.socket?.send(message);this.queue=[];return}const content=event.serverContent;if(content?.interrupted){this.sendTwilio({event:'clear',streamSid:this.streamSid});return}for(const part of content?.modelTurn?.parts??[]){const inline=part.inlineData??part.inline_data;if(!inline?.data||!String(inline.mimeType??inline.mime_type).startsWith('audio/pcm'))continue;const mulaw=pcm16ToMulaw(resamplePcm16(Buffer.from(inline.data,'base64'),24000,8000));for(const frame of chunkBuffer(mulaw,160))this.sendTwilio({event:'media',streamSid:this.streamSid,media:{payload:frame.toString('base64')}});this.sendTwilio({event:'mark',streamSid:this.streamSid,mark:{name:`gemini-${Date.now()}`}})}}
  close(){this.closed=true;this.queue=[];if(this.socket?.readyState===WebSocket.OPEN){this.socket.send(JSON.stringify({realtimeInput:{audioStreamEnd:true}}));this.socket.close(1000)}else this.socket?.terminate()}
}
