import type { Server } from 'node:http';
import { randomUUID } from 'node:crypto';
import { WebSocketServer, WebSocket } from 'ws';
import { db } from './db.js';
import { verifyStreamToken } from './twilio.js';
import { GeminiLivePhoneBridge } from './gemini-live.js';
type SessionIdentity={workspaceId:string;callSid:string};
function voiceContext(workspaceId:string){const workspace=db.prepare('SELECT name,industry FROM workspaces WHERE id=?').get(workspaceId);const settings=db.prepare('SELECT description,address,opening_time,closing_time FROM business_settings WHERE workspace_id=?').get(workspaceId);const agent=db.prepare('SELECT name,system_prompt,languages FROM agents WHERE workspace_id=? LIMIT 1').get(workspaceId);const services=db.prepare('SELECT name,duration_minutes,price_paise FROM services WHERE workspace_id=? AND active=1 LIMIT 30').all(workspaceId);const knowledge=db.prepare('SELECT question,answer FROM knowledge_entries WHERE workspace_id=? LIMIT 40').all(workspaceId);return `You are the multilingual phone receptionist for this business. Speak naturally in the caller's language and keep replies concise. Never invent facts or claim actions succeeded without tool confirmation. Business context: ${JSON.stringify({workspace,settings,agent,services,knowledge})}`}
export class TwilioMediaSession{
  private streamSid='';private recordId='';private startedAt=Date.now();private audioBytes=0;private stopped=false;private bridge?:GeminiLivePhoneBridge;
  constructor(private identity:SessionIdentity,private sendOutbound?:(message:object)=>void){}
  handle(raw:string){const message=JSON.parse(raw);if(message.event==='start')return this.start(message);if(message.event==='media')return this.media(message);if(message.event==='stop')return this.stop();if(message.event==='mark'||message.event==='dtmf')return {event:message.event};throw new Error('Unsupported Twilio media event')}
  private start(message:any){if(message.start?.callSid!==this.identity.callSid)throw new Error('Call identity mismatch');this.streamSid=String(message.start?.streamSid??message.streamSid??'');if(!this.streamSid)throw new Error('Missing stream SID');this.startedAt=Date.now();this.recordId=randomUUID();db.prepare(`INSERT INTO calls (id,workspace_id,caller_name,caller_phone,direction,status,outcome,summary,sentiment,duration_seconds,started_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(this.recordId,this.identity.workspaceId,'Phone caller',null,'inbound','in_progress',null,null,'neutral',0,new Date(this.startedAt).toISOString());if(this.sendOutbound){this.bridge=new GeminiLivePhoneBridge(voiceContext(this.identity.workspaceId),this.streamSid,this.sendOutbound);this.bridge.connect()}return {event:'started',recordId:this.recordId,streamSid:this.streamSid}}
  private media(message:any){if(!this.recordId)throw new Error('Media received before start');if(message.streamSid&&message.streamSid!==this.streamSid)throw new Error('Stream identity mismatch');const payload=String(message.media?.payload??'');if(payload.length>65536)throw new Error('Audio frame too large');this.audioBytes+=Buffer.byteLength(payload,'base64');this.bridge?.sendMulaw(payload);return {event:'media',audioBytes:this.audioBytes}}
  stop(){if(this.stopped)return {event:'stopped',recordId:this.recordId};this.stopped=true;this.bridge?.close();if(this.recordId){const duration=Math.max(1,Math.round((Date.now()-this.startedAt)/1000)),audioSeconds=Math.round(this.audioBytes/8000);db.prepare('UPDATE calls SET status=?,outcome=?,summary=?,duration_seconds=? WHERE id=? AND workspace_id=?').run('completed','incomplete',`Phone media session received approximately ${audioSeconds} seconds of caller audio.`,duration,this.recordId,this.identity.workspaceId)}return {event:'stopped',recordId:this.recordId,audioBytes:this.audioBytes}}
}
export function attachTelephonyGateway(server:Server){const gateway=new WebSocketServer({noServer:true,maxPayload:128*1024,perMessageDeflate:false});server.on('upgrade',async(request,socket,head)=>{try{const url=new URL(request.url??'','http://localhost');if(url.pathname!=='/telephony/stream')return socket.destroy();const token=url.searchParams.get('token');if(!token)throw new Error('Missing stream token');const claims=await verifyStreamToken(token);gateway.handleUpgrade(request,socket,head,ws=>gateway.emit('connection',ws,{workspaceId:String(claims.workspaceId),callSid:String(claims.callSid)}))}catch{socket.write('HTTP/1.1 401 Unauthorized\r\nConnection: close\r\n\r\n');socket.destroy()}});gateway.on('connection',(ws:WebSocket,identity:SessionIdentity)=>{const session=new TwilioMediaSession(identity,message=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(message))});let alive=true;ws.on('pong',()=>alive=true);ws.on('message',data=>{try{session.handle(data.toString())}catch{ws.close(1008,'Invalid media message')}});ws.on('close',()=>session.stop());const heartbeat=setInterval(()=>{if(!alive)return ws.terminate();alive=false;ws.ping()},20000);ws.on('close',()=>clearInterval(heartbeat))});return gateway}
