import { FormEvent, useEffect, useState } from 'react';
import { BookOpen, Building2, Check, Clock3, IndianRupee, Languages, Plus, Save, Sparkles } from 'lucide-react';
import { addKnowledge, addService, getSetup, saveAgent, saveBusiness } from './api';

export function AgentStudio(){
  const [data,setData]=useState<any>(null);const [tab,setTab]=useState<'business'|'agent'|'services'|'knowledge'>('business');const [notice,setNotice]=useState('');
  const refresh=()=>getSetup().then(setData).catch(()=>setNotice('Could not load workspace.'));
  useEffect(()=>{void refresh()},[]);
  async function submitBusiness(e:FormEvent<HTMLFormElement>){e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));await saveBusiness(v);flash('Business profile saved')}
  async function submitAgent(e:FormEvent<HTMLFormElement>){e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));await saveAgent({name:v.name,systemPrompt:v.systemPrompt,languages:['hi-IN','en-IN']});flash('Agent personality saved')}
  async function submitService(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,v=Object.fromEntries(new FormData(f));await addService({name:v.name,durationMinutes:Number(v.durationMinutes),priceRupees:v.priceRupees?Number(v.priceRupees):null});f.reset();await refresh();flash('Service added')}
  async function submitKnowledge(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,v=Object.fromEntries(new FormData(f));await addKnowledge(v);f.reset();await refresh();flash('Answer added to knowledge base')}
  function flash(text:string){setNotice(text);setTimeout(()=>setNotice(''),2600)}
  if(!data)return <div className="studio-loading"><Sparkles/>Loading your workspace…</div>;
  const settings=data.settings??{};
  return <section className="studio">
    <div className="studio-hero"><div><span className="eyebrow">AGENT STUDIO</span><h2>Teach your AI how your business works.</h2><p>Everything your receptionist needs to answer accurately and take the right action.</p></div><div className="setup-score"><b>62%</b><span>Setup complete</span><i><em></em></i></div></div>
    {notice&&<div className="save-notice"><Check size={15}/>{notice}</div>}
    <div className="studio-layout"><aside className="studio-tabs">
      <button className={tab==='business'?'selected':''} onClick={()=>setTab('business')}><Building2/><span><b>Business profile</b><small>Identity, contact and hours</small></span></button>
      <button className={tab==='agent'?'selected':''} onClick={()=>setTab('agent')}><Sparkles/><span><b>Agent personality</b><small>Name, languages and behaviour</small></span></button>
      <button className={tab==='services'?'selected':''} onClick={()=>setTab('services')}><Clock3/><span><b>Services & pricing</b><small>What customers can book</small></span></button>
      <button className={tab==='knowledge'?'selected':''} onClick={()=>setTab('knowledge')}><BookOpen/><span><b>Knowledge base</b><small>Frequently asked questions</small></span></button>
    </aside><div className="studio-card">
      {tab==='business'&&<form onSubmit={submitBusiness}><FormTitle icon={Building2} title="Business profile" text="Used by the agent while introducing your business and answering callers."/><div className="form-grid"><Field label="Business name"><input name="name" defaultValue={data.workspace.name} required/></Field><Field label="Business phone"><input name="phone" defaultValue={settings.phone} placeholder="+91…"/></Field><Field label="Opening time"><input type="time" name="openingTime" defaultValue={settings.opening_time}/></Field><Field label="Closing time"><input type="time" name="closingTime" defaultValue={settings.closing_time}/></Field><Field label="Human transfer number"><input name="transferNumber" defaultValue={settings.transfer_number} placeholder="Escalations go here"/></Field><Field label="Address"><input name="address" defaultValue={settings.address} placeholder="Business location"/></Field></div><Field label="Short business description"><textarea name="description" defaultValue={settings.description} placeholder="What does your business do, and who do you serve?"/></Field><SaveButton/></form>}
      {tab==='agent'&&<form onSubmit={submitAgent}><FormTitle icon={Sparkles} title="Agent personality" text="Shape how your receptionist speaks, behaves and handles uncertainty."/><div className="form-grid"><Field label="Agent name"><input name="name" defaultValue={data.agent.name} required/></Field><Field label="Languages"><div className="language-pills"><span><Languages/>Hindi</span><span><Languages/>English</span></div></Field></div><Field label="Core instructions"><textarea className="tall" name="systemPrompt" defaultValue={data.agent.system_prompt} minLength={20} required/></Field><div className="guardrail"><b>Built-in safety</b><p>The agent will never claim a booking or action succeeded unless the connected tool confirms it.</p></div><SaveButton/></form>}
      {tab==='services'&&<><FormTitle icon={Clock3} title="Services & pricing" text="Add services callers can ask about or book."/><form className="inline-add" onSubmit={submitService}><input name="name" placeholder="Service name" required/><input name="durationMinutes" type="number" min="5" defaultValue="30" placeholder="Minutes" required/><div className="price-input"><IndianRupee/><input name="priceRupees" type="number" min="0" placeholder="Price"/></div><button><Plus/>Add</button></form><div className="item-list">{data.services.length?data.services.map((s:any)=><div className="service-row" key={s.id}><i><Clock3/></i><span><b>{s.name}</b><small>{s.duration_minutes} minutes</small></span><strong>{s.price_paise==null?'Ask on call':`₹${(s.price_paise/100).toLocaleString('en-IN')}`}</strong></div>):<Empty text="No services yet. Add the first service callers can book."/>}</div></>}
      {tab==='knowledge'&&<><FormTitle icon={BookOpen} title="Knowledge base" text="Add trusted answers so your agent never has to guess."/><form className="knowledge-add" onSubmit={submitKnowledge}><Field label="Caller question"><input name="question" placeholder="Do you accept walk-ins?" required/></Field><Field label="Approved answer"><textarea name="answer" placeholder="Yes, but appointments receive priority…" required/></Field><button><Plus/>Add answer</button></form><div className="faq-list">{data.knowledge.length?data.knowledge.map((k:any)=><div key={k.id}><b>{k.question}</b><p>{k.answer}</p></div>):<Empty text="No answers yet. Add common questions your staff receives."/>}</div></>}
    </div></div>
  </section>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="studio-field"><span>{label}</span>{children}</label>}
function FormTitle({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string}){return <div className="form-title"><i><Icon/></i><div><h3>{title}</h3><p>{text}</p></div></div>}
function SaveButton(){return <button className="save-button"><Save/>Save changes</button>}
function Empty({text}:{text:string}){return <div className="empty-state"><BookOpen/><p>{text}</p></div>}
