import { FormEvent, useEffect, useMemo, useState } from 'react';
import { CalendarCheck, CalendarPlus, Check, ChevronDown, Clock3, Plus, Search, UserRound, X } from 'lucide-react';
import { createAppointment, getAppointments, getSetup, updateAppointmentStatus } from './api';

export function AppointmentsPage(){
  const [items,setItems]=useState<any[]>([]);const [services,setServices]=useState<any[]>([]);const [open,setOpen]=useState(false);const [query,setQuery]=useState('');const [notice,setNotice]=useState('');
  const load=()=>Promise.all([getAppointments(),getSetup()]).then(([a,s])=>{setItems(a.appointments);setServices(s.services)});
  useEffect(()=>{void load()},[]);
  const stats=useMemo(()=>({upcoming:items.filter(x=>new Date(x.starts_at)>=new Date()&&x.status==='confirmed').length,completed:items.filter(x=>x.status==='completed').length,cancelled:items.filter(x=>x.status==='cancelled').length}),[items]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,v=Object.fromEntries(new FormData(f));await createAppointment({customerName:v.customerName,service:v.service,startsAt:new Date(String(v.startsAt)).toISOString()});setOpen(false);f.reset();await load();flash('Appointment created')}
  async function change(id:string,status:string){await updateAppointmentStatus(id,status);await load();flash('Appointment updated')}
  function flash(t:string){setNotice(t);setTimeout(()=>setNotice(''),2200)}
  const filtered=items.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));
  return <section className="appointments-page">{notice&&<div className="save-notice"><Check/>{notice}</div>}<div className="appointments-head"><div><span className="eyebrow">SCHEDULE</span><h2>Appointments</h2><p>Bookings created by your AI agent and your team, together.</p></div><button className="primary" onClick={()=>setOpen(true)}><CalendarPlus/>New appointment</button></div><div className="appointment-metrics"><Metric label="Upcoming" value={stats.upcoming} tone="green"/><Metric label="Completed" value={stats.completed} tone="blue"/><Metric label="Cancelled" value={stats.cancelled} tone="sand"/></div><div className="appointment-board"><div className="ops-toolbar"><div><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search appointments…"/></div><span>{items.length} total</span></div>{filtered.length?<div className="appointment-list"><div className="appointment-table labels"><span>DATE & TIME</span><span>CUSTOMER</span><span>SERVICE</span><span>STATUS</span><span></span></div>{filtered.map(item=><div className="appointment-table" key={item.id}><span className="date-cell"><i>{new Date(item.starts_at).getDate()}</i><em><b>{new Date(item.starts_at).toLocaleDateString('en-IN',{month:'short',year:'numeric'})}</b><small>{new Date(item.starts_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</small></em></span><span className="customer-cell"><UserRound/><b>{item.customer_name}</b></span><span>{item.service}</span><span><mark className={item.status}>{item.status.replace('_',' ')}</mark></span><span className="status-select"><select value={item.status} onChange={e=>change(item.id,e.target.value)}><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No show</option></select><ChevronDown/></span></div>)}</div>:<div className="ops-empty"><CalendarCheck/><h3>No appointments yet</h3><p>Create one manually or let your AI receptionist book it.</p></div>}</div>{open&&<div className="modal-backdrop"><form className="booking-modal" onSubmit={create}><div className="booking-title"><div><i><CalendarPlus/></i><span><h3>New appointment</h3><p>Add a confirmed booking to the calendar.</p></span></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><label>Customer name<input name="customerName" required placeholder="Full name"/></label><label>Service<select name="service" required>{services.length?services.map(s=><option key={s.id}>{s.name}</option>):<option>General consultation</option>}</select></label><label>Date and time<input type="datetime-local" name="startsAt" required/></label><button className="create-booking"><Plus/>Create appointment</button></form></div>}</section>
}
function Metric({label,value,tone}:{label:string;value:number;tone:string}){return <div className="appt-metric"><i className={tone}><Clock3/></i><span><small>{label}</small><b>{value}</b></span></div>}
