import { FormEvent, useState } from 'react';
import { ArrowRight, Check, PhoneCall, ShieldCheck, Sparkles } from 'lucide-react';
import { login, register, Session } from './api';

export function AuthScreen({onDone}:{onDone:(session:Session)=>void}) {
  const [mode,setMode]=useState<'register'|'login'>('register');
  const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const values=Object.fromEntries(new FormData(e.currentTarget));try{const session=mode==='register'?await register(values):await login(values);localStorage.setItem('nayi_token',session.token);localStorage.setItem('nayi_user',JSON.stringify(session.user));onDone(session)}catch(err){setError(err instanceof Error?err.message:'Unable to continue')}finally{setLoading(false)}}
  return <div className="auth-page"><section className="auth-story"><div className="brand auth-brand"><div className="brand-mark"><PhoneCall size={19}/></div><span>Nayi Voice</span><b>private beta</b></div><div className="auth-message"><span className="eyebrow light">AI FRONT DESK FOR REAL BUSINESSES</span><h1>Every call answered.<br/>Every opportunity remembered.</h1><p>A multilingual AI teammate that handles enquiries, books appointments and knows when a human should step in.</p><ul><li><Check/>Hindi + English conversations</li><li><Check/>Appointments and follow-ups</li><li><Check/>Privacy-first business workspace</li></ul></div><div className="auth-quote">“Built for the way Indian businesses actually speak and work.”</div></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><div className="form-icon"><Sparkles/></div><h2>{mode==='register'?'Create your workspace':'Welcome back'}</h2><p>{mode==='register'?'Set up your first AI receptionist in under two minutes.':'Sign in to manage your calls and agent.'}</p>{mode==='register'&&<><label>Your name<input name="name" placeholder="e.g. Arjun Kapoor" required minLength={2}/></label><label>Business name<input name="businessName" placeholder="e.g. Aura Dental Clinic" required minLength={2}/></label><label>Industry<select name="industry" defaultValue="clinic"><option value="clinic">Clinic / Healthcare</option><option value="salon">Salon / Wellness</option><option value="real-estate">Real estate</option><option value="services">Professional services</option><option value="other">Other</option></select></label></>}<label>Work email<input name="email" type="email" placeholder="you@business.com" required/></label><label>Password<input name="password" type="password" placeholder="Minimum 8 characters" required minLength={8}/></label>{error&&<div className="form-error">{error}</div>}<button className="auth-submit" disabled={loading}>{loading?'Please wait…':mode==='register'?'Create workspace':'Sign in'}<ArrowRight size={17}/></button><div className="safe-note"><ShieldCheck size={15}/>Your credentials stay encrypted and private.</div><div className="switch-mode">{mode==='register'?'Already have an account?':'New to Nayi Voice?'} <button type="button" onClick={()=>{setMode(mode==='register'?'login':'register');setError('')}}>{mode==='register'?'Sign in':'Create workspace'}</button></div></form></section></div>
}
