import { useEffect, useState } from 'react';
import { ArrowUpRight, CalendarPlus, Clock3, PhoneCall, Search, UserRound, Users } from 'lucide-react';
import { getCalls, getCustomers } from './api';

export function OperationsPage({view}:{view:'Calls'|'Customers'}){
  const [rows,setRows]=useState<any[]>([]);const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);
  useEffect(()=>{setLoading(true);(view==='Calls'?getCalls().then(r=>setRows(r.calls)):getCustomers().then(r=>setRows(r.customers))).finally(()=>setLoading(false))},[view]);
  const filtered=rows.filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase()));
  return <section className="operations"><div className="operations-head"><div><span className="eyebrow">CUSTOMER OPERATIONS</span><h2>{view==='Calls'?'Call history':'Customer directory'}</h2><p>{view==='Calls'?'Search conversations, outcomes and follow-ups.':'Every caller becomes a reusable customer relationship.'}</p></div><button className="primary">{view==='Calls'?<PhoneCall/>:<CalendarPlus/>}{view==='Calls'?'Start browser test':'Add appointment'}</button></div><div className="ops-toolbar"><div><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${view.toLowerCase()}…`}/></div><span>{rows.length} {view.toLowerCase()}</span></div><div className="ops-card">{loading?<div className="ops-empty">Loading…</div>:filtered.length===0?<Empty view={view}/>:view==='Calls'?<CallRows rows={filtered}/>:<CustomerRows rows={filtered}/>}</div></section>
}
function Empty({view}:{view:string}){return <div className="ops-empty">{view==='Calls'?<PhoneCall/>:<Users/>}<h3>{view==='Calls'?'No calls yet':'No customers yet'}</h3><p>{view==='Calls'?'Your first browser test or connected phone call will appear here.':'Customers are created automatically when calls arrive.'}</p></div>}
function CallRows({rows}:{rows:any[]}){return <><div className="ops-row ops-label"><span>CALLER</span><span>OUTCOME</span><span>STARTED</span><span>DURATION</span><span></span></div>{rows.map(row=><div className="ops-row" key={row.id}><span className="ops-person"><i><PhoneCall/></i><em><b>{row.caller_name||'Unknown caller'}</b><small>{row.caller_phone||'Browser test'}</small></em></span><span><mark>{(row.outcome||row.status).replaceAll('_',' ')}</mark></span><span>{new Date(row.started_at).toLocaleString('en-IN')}</span><span><Clock3/>{Math.floor(row.duration_seconds/60)}m {row.duration_seconds%60}s</span><button><ArrowUpRight/></button></div>)}</>}
function CustomerRows({rows}:{rows:any[]}){return <><div className="ops-row customer-row ops-label"><span>CUSTOMER</span><span>LAST CONTACT</span><span>CALLS</span><span>BOOKINGS</span><span></span></div>{rows.map(row=><div className="ops-row customer-row" key={row.phone}><span className="ops-person"><i><UserRound/></i><em><b>{row.name}</b><small>{row.phone}</small></em></span><span>{new Date(row.last_contact).toLocaleDateString('en-IN')}</span><span>{row.total_calls}</span><span>{row.bookings}</span><button><ArrowUpRight/></button></div>)}</>}
