import { useEffect, useRef, useState } from 'react';
import { Mic, MicOff, PhoneOff, Sparkles, Volume2, X } from 'lucide-react';
import { askAgent, transcribeAudio } from './api';

type Line={role:'user'|'assistant';content:string};
export function VoiceLab({onClose}:{onClose:()=>void}){
  const [lines,setLines]=useState<Line[]>([{role:'assistant',content:'Namaste! Main Meera bol rahi hoon. Main aapki kaise madad kar sakti hoon?'}]);
  const [listening,setListening]=useState(false);const [busy,setBusy]=useState(false);const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const chunks=useRef<Blob[]>([]);
  useEffect(()=>{speak(lines[0].content);return()=>{speechSynthesis.cancel();stream.current?.getTracks().forEach(t=>t.stop())}},[]);
  function speak(text:string){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='hi-IN';utterance.rate=.98;speechSynthesis.speak(utterance)}
  async function send(message:string){const next=[...lines,{role:'user' as const,content:message}];setLines(next);setBusy(true);try{const result=await askAgent(message,next.slice(-8));const updated=[...next,{role:'assistant' as const,content:result.reply}];setLines(updated);speak(result.reply)}catch{const reply='Main abhi server se connect nahi kar pa rahi. Kripya ek baar phir try karein.';setLines([...next,{role:'assistant',content:reply}]);speak(reply)}finally{setBusy(false)}}
  async function toggle(){if(listening){recorder.current?.stop();setListening(false);return}try{speechSynthesis.cancel();const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream.current=media;chunks.current=[];const preferred=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';const r=new MediaRecorder(media,{mimeType:preferred});recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{media.getTracks().forEach(t=>t.stop());setBusy(true);try{const transcript=await transcribeAudio(new Blob(chunks.current,{type:preferred}));if(transcript.text.trim())await send(transcript.text.trim())}catch{const reply='Audio samajhne mein problem hui. Kripya dobara boliye.';setLines(current=>[...current,{role:'assistant',content:reply}]);speak(reply)}finally{setBusy(false)}};r.start();setListening(true)}catch{alert('Microphone permission is required for the voice test.')}}
  return <div className="modal-backdrop"><div className="voice-lab"><div className="voice-head"><div><span><Sparkles size={16}/> GROQ WHISPER VOICE TEST</span><h2>Talk to Meera</h2></div><button onClick={onClose}><X/></button></div><div className="voice-orb"><i className={listening?'pulse':''}><Volume2/></i><strong>{listening?'Recording — tap to send':busy?'Transcribing & thinking…':'Ready to talk'}</strong><small>Encrypted API request · no phone charges</small></div><div className="transcript">{lines.map((line,i)=><div key={i} className={`bubble ${line.role}`}>{line.content}</div>)}</div><div className="voice-controls"><button className={listening?'mic active':'mic'} onClick={toggle} disabled={busy}>{listening?<MicOff/>:<Mic/>}</button><button className="hangup" onClick={onClose}><PhoneOff/></button></div><p className="voice-hint">Tap once to record, speak in Hindi/Hinglish/English, then tap again to send.</p></div></div>
}
